# Generated by Django 5.0.1 on 2024-01-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTable',
            new_name='RoomTable',
        ),
    ]
